export const REDUX_CONSTANTS = {
    //login
    SET_AUTH_USER: "SET_AUTH_USER",
    UNSET_AUTH_USER: "UNSET_AUTH_USER",
    SET_TOKEN: "SET_TOKEN",
    UNSET_TOKEN: "UNSET_TOKEN",
    SET_GROUP_DETAILS: "SET_GROUP_DETAILS",
    UNSET_GROUP_DETAILS: "UNSET_GROUP_DETAILS",

    //logger 
    LOG_APP_STATE:'LOG_APP_STATE',

    //container
    SET_MYCONTAINERS_LIST:'SET_MYCONTAINERS_LIST',
    UNSET_MYCONTAINERS_LIST:'UNSET_MYCONTAINERS_LIST',
    SET_CURRENT_CONTAINER:'SET_CURRENT_CONTAINER',
    UNSET_CURRENT_CONTAINER:'UNSET_CURRENT_CONTAINER',
    SET_CURRENT_BOX:'SET_CURRENT_BOX',
    UNSET_CURRENT_BOX:'UNSET_CURRENT_BOX',

}