
export const LOGIN_CONSTANTS = {
    LOGIN_USER: "LOGIN_USER",
    SET_AUTH_USER: "SET_AUTH_USER",
    LOGOUT_USER: "LOGOUT_USER",
    CLEAR_AUTH_USER: "CLEAR_AUTH_USER",
    SET_TOKEN: "SET_TOKEN"
}